version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    hostname: kafka-manager
    networks: 
      - zookeeper_some-net
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2182,zoo3:2183
      APPLICATION_SECRET: random-secret
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: itdotaer
      KAFKA_MANAGER_PASSWORD: itdotaer
networks: 
  zookeeper_some-net:
    external: true