version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    hostname: kafka_manager
    container_name: kafka_manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zoo1:2184,zoo2:2185,zoo3:2186
      APPLICATION_SECRET: random-secret
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: itdotaer
      KAFKA_MANAGER_PASSWORD: itdotaer
    networks:
      br17219:
        ipv4_address: 172.19.0.17
networks:
  br17219:
    external: 
      name: br17219