version: '2'
services:
  kafka-1:
    image: wurstmeister/kafka:latest
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.14
  kafka-2:
    image: wurstmeister/kafka:latest
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.15
  kafka-3:
    image: wurstmeister/kafka:latest
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - 9095:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka-3
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.16
networks:
  br17219:
    external: 
      name: br17219