version: '2'
services:
  kafka1:
    image: wurstmeister/kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.14
  kafka2:
    image: wurstmeister/kafka:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.15
  kafka3:
    image: wurstmeister/kafka:latest
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9095:9095
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9095
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    external_links: 
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17219:
        ipv4_address: 172.19.0.16
networks:
  br17219:
    external: 
      name: br17219